### ISSUE TITLE
Installation instructions and example data

### ISSUE THREAD

**Issue by bilke** [joergbuchwald/VTUinterface#12]
Some comments:

1. You can simplify installation instructions to just this line:

```bash
pip install [--user] https://github.com/joergbuchwald/VTUinterface/archive/refs/heads/master.zip
```

2. When following the `README_python.md` the file `examples/square2d_random.vtu` is missing in the repo. It would be nice if you would provide it (although you mention that it can be generated with another tool).

**Comment by joergbuchwald** [comment]
fixed by last two commits in master
