### ISSUE TITLE
JOSS review suggestions

### ISSUE THREAD

**Issue by cpgr** [joergbuchwald/VTUinterface#14]
This looks like it may useful for many people.

Like joergbuchwald/ogs6py#17, I have some suggestions

- Some documentation on how to run the tests to make sure everything is working would be good
- `examples/vtu_read_example.py` - throws an error `AttributeError: 'VTUIO' object has no attribute 'get_point_data'`
- The images don't appear in the documentation, e.g. https://joergbuchwald.github.io/VTUinterface-doc/basic_usage_python.html#reading-point-set-data-from-pvd-files doesn't display images for me
- I do get some performance warnings that you might want to consider
```vtuIO.py:102: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df["r_"+str(i)] = (df[x]-val[x]) * (df[x]-val[x]) + (df[y]-val[y]) * (df[y]-val[y])```
- There is a typo in the fourth bullet point in `3. FAQ/Troubleshooting`: ...this can be resolved bei using...
- The changelog references `ogs6py`, possible cut and paste error.

Otherwise, the documentation is good, particularly the API class documentation.

Note: I didn't try this in julia.

Refs openjournals/joss-reviews#3673

**Comment by joergbuchwald** [comment]
Thank you very much for your suggestions that I will consider.
Concerning the performance warning, I'm not quite sure, I tried the following implementation using pd.concat instead
```python
df = pd.DataFrame(points)
dfnew = pd.concat([df, pd.concat([pd.DataFrame(((df[0]-val[0]) * (df[0]-val[0]) + (df[1]-val[1]) * (df[1]-val[1])+ (df[2]-val[2]) * (df[2]-val[2])), columns = ["r_"+str(i)]) for i, (_, val) in enumerate(points_interpol.items())], axis=1)], axis=1) 
```
with 8 interpolation points and 10000 repetitions it resulted in slightly worse performance on average.

**Comment by cpgr** [comment]
I didn't really notice any performance issues, but just wanted to let you know about that warning I received. Feel free to close this issue off.
